import { cases } from "@/libs/const";
import { ICase } from "@/libs/types";
import { ChevronRight } from "@mui/icons-material";
import {
  Box,
  Card,
  CardActionArea,
  Container,
  Grid,
  IconButton,
  Typography,
} from "@mui/material";
import Head from "next/head";
import Link from "next/link";

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <Container sx={{ my: 2 }}>
          {cases.map((c, i) => (
            <Case {...c} key={i} />
          ))}
        </Container>
      </main>
    </>
  );
}

function Case({ title, subTitle, description, slug }: ICase) {
  return (
    <Card sx={{ my: 2 }}>
      <CardActionArea LinkComponent={Link} href={`/${slug}`}>
        <Box sx={{ p: 2 }}>
          <Grid container spacing={2}>
            <Grid item xs={12} sm={3}>
              <Typography variant="h3">{title}</Typography>
            </Grid>
            <Grid item xs>
              <Typography variant="h4" sx={{ mb: 2 }}>
                {subTitle}
              </Typography>
              <Typography variant="body1">{description}</Typography>
            </Grid>
          </Grid>
          <Box sx={{ textAlign: "right" }}>
            <IconButton sx={{ border: "1px solid #ddd" }}>
              <ChevronRight />
            </IconButton>
          </Box>
        </Box>
      </CardActionArea>
    </Card>
  );
}
